config/routes.rb
Bitcoindirectory::Application.routes.draw do

  resources :walletmaps

  get "welcome/index"
  root "welcome#index"  

end

app/models/proof.rb
class Proof < ActiveRecord::Base
  belongs_to :walletmap
end

app/models/walletmap.rb
class Walletmap < ActiveRecord::Base
  has_many :proofs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/proofs_controller.rb
class ProofsController < ApplicationController
  def create
    @walletmap = WalletMap.find(params[:post_id])
    @proof = @walletmap.proofs.create(params[:comment].permit(:commenter, :body))
    redirect_to walletmap_path(@post)
  end  
end

app/controllers/walletmaps_controller.rb
class WalletmapsController < ApplicationController
  before_action :set_walletmap, only: [:show, :edit, :update, :destroy]

  # GET /walletmaps
  # GET /walletmaps.json
  def index
    @walletmaps = Walletmap.all
  end

  # GET /walletmaps/1
  # GET /walletmaps/1.json
  def show
  end

  # GET /walletmaps/new
  def new
    @walletmap = Walletmap.new
  end

  # GET /walletmaps/1/edit
  def edit
  end

  # POST /walletmaps
  # POST /walletmaps.json
  def create
    @walletmap = Walletmap.new(walletmap_params)

    respond_to do |format|
      if @walletmap.save
        format.html { redirect_to @walletmap, notice: 'Walletmap was successfully created.' }
        format.json { render action: 'show', status: :created, location: @walletmap }
      else
        format.html { render action: 'new' }
        format.json { render json: @walletmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walletmaps/1
  # PATCH/PUT /walletmaps/1.json
  def update
    respond_to do |format|
      if @walletmap.update(walletmap_params)
        format.html { redirect_to @walletmap, notice: 'Walletmap was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @walletmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walletmaps/1
  # DELETE /walletmaps/1.json
  def destroy
    @walletmap.destroy
    respond_to do |format|
      format.html { redirect_to walletmaps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_walletmap
      @walletmap = Walletmap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def walletmap_params
      params.require(:walletmap).permit(:wallet, :address, :address_type)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/walletmaps_helper.rb
module WalletmapsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Bitcoin Directory" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/proofs/_form.html.erb
<h6>Add Proof</h6>
<%= form_for([@walletmap, @walletmap.proofs.build]) do |f| %>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/walletmaps/_form.html.erb
<%= form_for(@walletmap) do |f| %>
  <% if @walletmap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@walletmap.errors.count, "error") %> prohibited this walletmap from being saved:</h2>

      <ul>
      <% @walletmap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wallet %><br>
    <%= f.text_field :wallet %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address_type %><br>
    <%= f.text_field :address_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/walletmaps/edit.html.erb
<h1>Editing walletmap</h1>

<%= render 'form' %>

<%= link_to 'Show', @walletmap %> |
<%= link_to 'Back', walletmaps_path %>

app/views/walletmaps/index.html.erb
<h1>Listing walletmaps</h1>

<table>
  <thead>
    <tr>
      <th>Wallet</th>
      <th>Address</th>
      <th>Address type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @walletmaps.each do |walletmap| %>
      <tr>
        <td><%= walletmap.wallet %></td>
        <td><%= walletmap.address %></td>
        <td><%= walletmap.address_type %></td>
        <td><%= link_to 'Show', walletmap %></td>
        <td><%= link_to 'Edit', edit_walletmap_path(walletmap) %></td>
        <td><%= link_to 'Destroy', walletmap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Walletmap', new_walletmap_path %>

app/views/walletmaps/new.html.erb
<h1>New walletmap</h1>

<%= render 'form' %>

<%= link_to 'Back', walletmaps_path %>

app/views/walletmaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wallet:</strong>
  <%= @walletmap.wallet %>
</p>

<p>
  <strong>Address:</strong>
  <%= @walletmap.address %>
</p>

<p>
  <strong>Address type:</strong>
  <%= @walletmap.address_type %>
</p>

<h4>Proofs that this is the wallet address</h4>
<%= render @walletmap.proofs %>
<%= render "proofs/form" %>


<%= link_to 'Edit', edit_walletmap_path(@walletmap) %> |
<%= link_to 'Back', walletmaps_path %>

app/views/welcome/index.html.erb
<h1>Welcome to the Bitcoin Directory</h1>
<p>Find me in app/views/welcome/index.html.erb</p>